### ISSUE TITLE
numpy 1.24.0 np.bool removed needs cleanup

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/pytroll-schedule#74]
With numpy 1.24.0 ( as far as I understand) np.bool ( and others) are removed.

This needs to be cleaned up.

**Comment by djhoese** [comment]
`np.float` too. I see one use of both:

https://github.com/pytroll/pytroll-schedule/blob/c765fb098638135303a2f5cb60bf14d2e2ed6923/trollsched/graph.py#L34-L35

**Comment by mraspaud** [comment]
Hopefully I can get this fixed in #72
